apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: lidiyaj/cartapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "31672"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  annotations:
   konghq.com/plugins: twelve-per-min
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32055